### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by darakian** [raybellis/ldns#1]
Hey, thanks for making the library, but all the examples show printing records to stdout. Is there a simple way to parse a resource record (rather the first entry in a resource record list) and to get an IP address from it as a string, int,  or other data structure?

**Comment by raybellis** [comment]
Can you elaborate more on what you're trying to do, since evldns doesn't normally get involved in parsing resource records (it serves answers, and doesn't make its own queries) ?

**Comment by raybellis** [comment]
You should address this to NLnet.labs and/or refer to their online documentation at https://www.nlnetlabs.nl/projects/ldns/doc/index.html - this copy here is just a patched fork of their library.
